const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('hub', {
  getData:        ()              => ipcRenderer.invoke('get-data'),
  addSource:      (source)        => ipcRenderer.invoke('add-source', source),
  removeSource:   (id)            => ipcRenderer.invoke('remove-source', id),
  refreshAll:     ()              => ipcRenderer.invoke('refresh-all'),
  markRead:       (id)            => ipcRenderer.invoke('mark-read', id),
  toggleSaved:    (id)            => ipcRenderer.invoke('toggle-saved', id),
  markAllRead:    (sourceId)      => ipcRenderer.invoke('mark-all-read', sourceId),
  saveNote:       (data)          => ipcRenderer.invoke('save-note', data),
  getNote:        (id)            => ipcRenderer.invoke('get-note', id),
  getBacklinks:   (id)            => ipcRenderer.invoke('get-backlinks', id),
  getAllLinks:     ()              => ipcRenderer.invoke('get-all-links'),
  getAllNotes:     ()              => ipcRenderer.invoke('get-all-notes'),
  searchNotes:    (q)             => ipcRenderer.invoke('search-notes', q),
  saveStandaloneNote: (data)      => ipcRenderer.invoke('save-standalone-note', data),
  deleteStandaloneNote: (id)      => ipcRenderer.invoke('delete-standalone-note', id),
  saveTags:       (id, tags)      => ipcRenderer.invoke('save-tags', id, tags),
  togglePriority: (sourceId)      => ipcRenderer.invoke('toggle-priority', sourceId),
  getSettings:    ()              => ipcRenderer.invoke('get-settings'),
  saveSettings:   (s)             => ipcRenderer.invoke('save-settings', s),
  addLink:        (link)          => ipcRenderer.invoke('add-link', link),
  getStats:       ()              => ipcRenderer.invoke('get-stats'),
  exportMarkdown: ()              => ipcRenderer.invoke('export-markdown'),
  exportOpml:     ()              => ipcRenderer.invoke('export-opml'),
  importOpml:     ()              => ipcRenderer.invoke('import-opml'),
  openExternal:   (url)           => ipcRenderer.invoke('open-external', url),
  onAutoRefresh:  (cb)            => ipcRenderer.on('auto-refresh-done', (_, data) => cb(data)),
  fetchReadable:  (url)           => ipcRenderer.invoke('fetch-readable', url),
  saveHighlight:  (data)          => ipcRenderer.invoke('save-highlight', data),
  getHighlights:  ()              => ipcRenderer.invoke('get-highlights'),
  reorderSources: (ids)           => ipcRenderer.invoke('reorder-sources', ids),
  toggleMute:     (id)            => ipcRenderer.invoke('toggle-mute', id),
  updateSource:   (id, updates)   => ipcRenderer.invoke('update-source', id, updates),
  validateFeed:   (url)           => ipcRenderer.invoke('validate-feed', url),
  getSourceStats: ()              => ipcRenderer.invoke('get-source-stats'),
  toggleLater:    (id)            => ipcRenderer.invoke('toggle-later', id),
})
